# Generated by Django 4.2.1 on 2023-07-09 09:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gener', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publish', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='IMG')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='Year')),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='Pages')),
                ('binding', models.CharField(blank=True, choices=[('hard', 'Hard'), ('soft', 'Soft'), ('info', 'NOINFO')], default='info', max_length=4, verbose_name='Binding')),
                ('formatt', models.CharField(choices=[('slarge', 'Slarge'), ('large', 'Large'), ('medium', 'Medium'), ('small', 'Small'), ('midget', 'Midget'), ('info', 'NOINFO')], default='info', max_length=6, verbose_name='Format')),
                ('isbn', models.CharField(blank=True, default=None, max_length=10, verbose_name='ISBN')),
                ('weight', models.IntegerField(blank=True, default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='Weight')),
                ('ager', models.IntegerField(blank=True, default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)], verbose_name='Ager')),
                ('quantity', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='quantity')),
                ('available', models.BooleanField(default=True, verbose_name='Availability')),
                ('rating', models.IntegerField(blank=True, default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rating')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last change')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.author', verbose_name='Author')),
                ('gener', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.gener', verbose_name='Gener')),
                ('publish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='books.publish', verbose_name='Publish')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.series', verbose_name='Series')),
            ],
        ),
    ]
