# Generated by Django 4.2.1 on 2023-05-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_author_gener_publish_series_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='login',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='gener',
            old_name='login',
            new_name='Gener',
        ),
        migrations.RenameField(
            model_name='publish',
            old_name='login',
            new_name='Publish',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='login',
            new_name='Series',
        ),
    ]
